#!/bin/bash
awk '{
	if(index($0,"<mime-type") != 0)A=1;
	if(index($0,"</mime-type>") != 0)A=2;
	if(A == 1){SP=SP sprintf( "%s",$0)}else{NumPatt=split(SP,GG,"glob pattern");
		for(I in GG)
		{		
		print substr(GG[I],index(GG[I],"glob pattern"));
		}
		SP=1}		
	}'  /usr/share/mime/packages/freedesktop.org.xml


#	| awk '{
#A=substr($0,index($0,"<comment>")+9);
#B=substr(A,0,index(A,"</comment>")-1);
#
#C=substr($0,index($0,"pattern=")+8);
#D=substr(C,0,index(C,">")-2);
#
#print B" ===  " D 
#}'
